ai_questions = [
    "What is artificial intelligence?",
    "How does AI work?",
    "What are the main types of AI?",
    "What is machine learning, and how is it related to AI?",
    "What is the difference between AI and automation?",
    "What are some common applications of AI in daily life?",
    "How does AI improve healthcare?",
    "Can AI help in education? How?",
    "How does AI influence social media?",
    "What are self-driving cars, and how do they use AI?",
    "What is neural network training?",
    "What is a dataset in AI, and why is it important?",
    "How do AI models learn?",
    "What is the role of algorithms in AI?",
    "What does 'deep learning' mean?",
    "How do chatbots like this one work?",
    "How does AI understand human language?",
    "What is computer vision in AI?",
    "How does an AI model like GPT process text?",
    "Can AI recognize images? How does it work?",
    "How does AI affect jobs?",
    "What are the benefits of using AI?",
    "Are there any risks associated with AI?",
    "How can AI improve business efficiency?",
    "Is AI ethical? Why or why not?",
    "What is the future of AI?",
    "Will AI ever surpass human intelligence?",
    "How close are we to creating general AI?",
    "Can AI create art? How does it do that?",
    "What are the latest trends in AI research?",
    "What are the biggest challenges in AI development?",
    "How does AI handle bias in data?",
    "What is overfitting in machine learning, and why is it a problem?",
    "How do AI systems stay secure?",
    "How does AI deal with incomplete or noisy data?",
    "Can AI write a poem or a story?",
    "How does AI play chess or other games?",
    "Can AI understand emotions?",
    "What is the most advanced AI today?",
    "Can AI learn new languages?"
    "What is the difference between supervised and unsupervised learning?",
    "What is reinforcement learning?",
    "What are the key components of a neural network?",
    "What is an activation function in AI?",
    "How does backpropagation work in neural networks?",
    "What is gradient descent in machine learning?",
    "What is a convolutional neural network (CNN)?",
    "How does a recurrent neural network (RNN) work?",
    "What are transformers in AI?",
    "What is the purpose of attention mechanisms in AI?",
    "What is overfitting, and how can it be avoided?",
    "What is underfitting in machine learning?",
    "What is cross-validation in machine learning?",
    "What are hyperparameters in AI models?",
    "How do you choose the best model for a problem?",
    "What is feature engineering?",
    "What are embeddings in AI?",
    "What is a pre-trained model in AI?",
    "How does transfer learning work?",
    "What is the difference between classification and regression?",
    "What is natural language processing (NLP)?",
    "How does AI translate languages?",
    "What is tokenization in NLP?",
    "What is the difference between tokens, words, and subwords in AI?",
    "What is a language model in AI?",
    "What is sentiment analysis?",
    "How does speech recognition work?",
    "What is named entity recognition (NER)?",
    "What is the Turing Test?",
    "What is an AI chatbot?",
    "What is explainable AI (XAI)?",
    "What is adversarial learning in AI?",
    "What is generative adversarial network (GAN)?",
    "How does AI create synthetic data?",
    "What are common evaluation metrics in AI?",
    "What is precision, recall, and F1-score in AI?",
    "What is accuracy in machine learning?",
    "How do you evaluate the performance of an AI model?",
    "What is the difference between training and testing data?",
    "What is a confusion matrix in AI?",
    "How do AI models handle missing data?",
    "What is clustering in machine learning?",
    "What is dimensionality reduction in AI?",
    "What is principal component analysis (PCA)?",
    "How does AI handle big data?",
    "What is edge AI?",
    "What is federated learning in AI?",
    "What is the role of GPUs in AI training?",
    "What is a sparse matrix in AI?",
    "What are decision trees in machine learning?",
    "What is random forest in AI?",
    "What is gradient boosting in machine learning?",
    "How does AI use ensemble methods?",
    "What is the ethical impact of AI?",
    "How can AI combat misinformation?",
    "What is the role of bias in AI models?",
    "How does AI ensure data privacy?",
    "What is responsible AI?",
    "What is the role of AI in climate change?",
    "How does AI optimize supply chains?",
    "Can AI predict human behavior?"
]

test_question = [
    "What are the main types of AI?",
    "Can AI predict human behavior?",
    "What is accuracy in machine learning?",
    "How does AI translate languages?",
    "What is edge AI?",
]